### make admin
POST http://localhost:8080/users
Content-Type: application/json

{
  "email" : "asdf2@naver.com",
  "nickname" : "admin",
  "password" : "asdf1234@!",
  "role" : "admin"
}

### make owner
POST http://localhost:8080/users
Content-Type: application/json

{
  "email" : "asdf3@naver.com",
  "nickname" : "owner",
  "password" : "asdf1234@!",
  "role" : "user"
}

### make manager
POST http://localhost:8080/users
Content-Type: application/json

{
  "email" : "asdf4@naver.com",
  "nickname" : "manager",
  "password" : "asdf1234@!",
  "role" : "user"
}

### make user
POST http://localhost:8080/users
Content-Type: application/json

{
  "email" : "asdf@naver.com",
  "nickname" : "user",
  "password" : "asdf1234@!",
  "role" : "user"
}

### login owner
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "email" : "asdf3@naver.com",
  "password" : "asdf1234@!"
}


### make new item
POST http://localhost:8080/items
Content-Type: application/json

{
"name":"book1",
"description":"description",
"managerId":3,
"ownerId":2
}
### make new item
POST http://localhost:8080/items
Content-Type: application/json

{
  "name":"book2",
  "description":"description",
  "managerId":3,
  "ownerId":2
}
### login user
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "email" : "asdf@naver.com",
  "password" : "asdf1234@!"
}

### make new resevation
POST http://localhost:8080/reservations
Content-Type: application/json

{
"itemId":1,
"userId":4,
"startAt":"2024-10-10T18:00:00",
"endAt":"2024-10-10T20:00:00"
}
### make new resevation
POST http://localhost:8080/reservations
Content-Type: application/json

{
  "itemId":2,
  "userId":3,
  "startAt":"2024-10-10T18:00:00",
  "endAt":"2024-10-10T20:00:00"
}

### login admin
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "email" : "asdf2@naver.com",
  "password" : "asdf1234@!"
}

### report all
POST http://localhost:8080/admins/report-users
Content-Type: application/json

{
  "userIds": [1,2,3,4]
}
### find all resevation
GET http://localhost:8080/reservations

### login owner
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "email" : "asdf3@naver.com",
  "password" : "asdf1234@!"
}

### find all reservation by userId and itemId
GET http://localhost:8080/reservations/search?
    userId=&
    itemId=1