name: CI/CD Pipeline

# 워크플로우 실행 조건
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

# 워크플로우 작업 정의
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. JDK 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # 3. Gradle 실행 권한 부여
      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      # 4. Gradle 빌드 및 테스트
      - name: create env
        run:  echo "${{ secrets.ENV }}" >> .env

      - name: Build and Test with Gradle
        run: ./gradlew build

      # 5. 도커 이미지 빌드 및 푸시 (선택사항)
      - name: Docker Build and Push
        if: github.ref == 'refs/heads/main'
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
          docker build -t your-dockerhub-username/your-app-name:latest .
          docker push your-dockerhub-username/your-app-name:latest